"""Réinitialisation des migrations

Revision ID: 9d96dcbb1523
Revises: a14c793d0d7c
Create Date: 2024-07-16 11:37:15.699272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d96dcbb1523'
down_revision = 'a14c793d0d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee') as batch_op:
        batch_op.create_unique_constraint('uq_employee_cin', ['cin'])
        batch_op.create_unique_constraint('uq_employee_matricule', ['matricule'])
        batch_op.create_unique_constraint('uq_employee_utilisateur', ['utilisateur'])
        batch_op.alter_column('username', existing_type=sa.String(50), nullable=False)
        batch_op.alter_column('jrs_restant', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('jrs_total', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('id_service', existing_type=sa.String(50), nullable=False)
        batch_op.alter_column('nom_entite', existing_type=sa.String(50), nullable=False)
        batch_op.alter_column('date_debut', existing_type=sa.Date(), nullable=False)
        batch_op.alter_column('date_naiss', existing_type=sa.Date(), nullable=False)
        batch_op.alter_column('adresse', existing_type=sa.String(100), nullable=False)
        batch_op.alter_column('mot_de_passe', existing_type=sa.String(50), nullable=False)
        batch_op.alter_column('utilisateur', existing_type=sa.String(50), nullable=False)
        batch_op.alter_column('responsable', existing_type=sa.String(50), nullable=False)
        batch_op.alter_column('prenom', existing_type=sa.String(50), nullable=False)
        batch_op.alter_column('nom', existing_type=sa.String(50), nullable=False)
        batch_op.alter_column('matricule', existing_type=sa.String(50), nullable=False)
        batch_op.alter_column('cin', existing_type=sa.String(50), nullable=False)
        batch_op.add_column(sa.Column('id_type_emp', sa.Integer, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee') as batch_op:
        batch_op.add_column(sa.Column('id_type_emp', sa.String(length=50), nullable=False))
        batch_op.alter_column('cin', existing_type=sa.String(length=50), nullable=False)
        batch_op.alter_column('matricule', existing_type=sa.String(length=50), nullable=False)
        batch_op.alter_column('nom', existing_type=sa.String(length=50), nullable=False)
        batch_op.alter_column('prenom', existing_type=sa.String(length=50), nullable=False)
        batch_op.alter_column('responsable', existing_type=sa.String(length=50), nullable=False)
        batch_op.alter_column('utilisateur', existing_type=sa.String(length=50), nullable=False)
        batch_op.alter_column('mot_de_passe', existing_type=sa.String(length=50), nullable=False)
        batch_op.alter_column('adresse', existing_type=sa.String(length=100), nullable=False)
        batch_op.alter_column('date_naiss', existing_type=sa.Date(), nullable=False)
        batch_op.alter_column('date_debut', existing_type=sa.Date(), nullable=False)
        batch_op.alter_column('nom_entite', existing_type=sa.String(length=50), nullable=False)
        batch_op.alter_column('id_service', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('jrs_total', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('jrs_restant', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('username', existing_type=sa.String(length=50), nullable=True)
        batch_op.add_column(sa.Column('grade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tel', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###
